apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - env:
        - name: test
          value: test
        - name: {{ env.name }}
          value: {{ env.value }}
        image: nginx
        name: nginx
